// Schema-shape tests for the per-operation README parser.
// Locks the contract the LLM has to honour. We don't hit the network here.

import { describe, expect, it } from 'vitest';
import { OperationReadme, renderReadmeAsMarkdown } from './compose-readme.js';

describe('OperationReadme', () => {
  const valid = {
    title: 'Candidate intake & rejection pipeline',
    oneLine: 'Every applicant gets a thoughtful reply within 24 hours, automatically.',
    whatItDoes:
      'Maya runs a recruiting site. When a candidate applies, this operation captures the form, scores fit, and either rejects them with a personalized note or forwards the strong ones to her hiring client.\n\nIt runs every weekday morning and writes to a private dashboard so Maya can spot-check before the auto-rejections go out.',
    howItWorks:
      'A form on the recruiting site posts to Argo. Argo runs a small classifier on each submission and decides reject / hold / forward. Strong candidates land in Maya\'s email with a one-click "approve to forward" button.\n\nWeak candidates get a personalised rejection email written in Maya\'s voice. Argo waits 4 minutes before sending so a human can intercept.',
    ifSomethingBreaks:
      'If a submission doesn\'t show up, check the public form URL in the workspace and resubmit. If the auto-reply has the wrong tone, edit the voice card in Scoping; the next reply will use the new style.\n\nIf anything serious breaks, Argo will email you with a proposed fix and three buttons: Approve, Edit, Decline. Repairs are never auto-applied.',
  };

  it('parses a fully valid readme', () => {
    const r = OperationReadme.safeParse(valid);
    expect(r.success).toBe(true);
  });

  it('rejects missing required sections', () => {
    const partial = { ...valid, ifSomethingBreaks: undefined } as unknown;
    const r = OperationReadme.safeParse(partial);
    expect(r.success).toBe(false);
  });

  it('rejects sections that are too short to be useful', () => {
    const tooShort = { ...valid, whatItDoes: 'It just works.' };
    const r = OperationReadme.safeParse(tooShort);
    expect(r.success).toBe(false);
  });

  it('rejects sections that exceed the upper bound', () => {
    const tooLong = { ...valid, whatItDoes: 'x'.repeat(2500) };
    const r = OperationReadme.safeParse(tooLong);
    expect(r.success).toBe(false);
  });

  it('rejects an oneLine that is too long for the hook', () => {
    const r = OperationReadme.safeParse({ ...valid, oneLine: 'x'.repeat(240) });
    expect(r.success).toBe(false);
  });

  it('renderReadmeAsMarkdown emits all three sections + headings', () => {
    const md = renderReadmeAsMarkdown(valid as OperationReadme);
    expect(md).toContain('# Candidate intake & rejection pipeline');
    expect(md).toContain('## What this does');
    expect(md).toContain('## How it works');
    expect(md).toContain('## If something breaks');
    expect(md).toContain('Generated by Argo');
  });
});
