import type { WorkflowMap } from '@argo/shared-types';
import type { TestCase } from '@argo/workspace-runtime';

/**
 * Generates the synthetic submission test suite from a WorkflowMap.
 *
 * Section 10: "TESTING — full end-to-end before any deployment goes live.
 * Synthetic submission → assert in DB → assert email content → simulate
 * approval → assert downstream → confirm digest is scheduled. A workflow
 * cannot transition to RUNNING unless every assertion is green."
 */
export function generateTestSuite(map: WorkflowMap): TestCase[] {
  const cases: TestCase[] = [];
  if (map.trigger.type === 'form_submission') {
    const happy: Record<string, unknown> = {};
    for (const f of map.trigger.fields) {
      switch (f.type) {
        case 'email':
          happy[f.id] = 'synth+happy@argo.local';
          break;
        case 'phone':
          happy[f.id] = '+15551234567';
          break;
        case 'number':
          happy[f.id] = 5;
          break;
        case 'url':
          happy[f.id] = 'https://example.com/synth';
          break;
        case 'date':
          happy[f.id] = new Date().toISOString().slice(0, 10);
          break;
        case 'select':
          happy[f.id] = f.options?.[0] ?? 'option_a';
          break;
        case 'multi_select':
          happy[f.id] = [f.options?.[0] ?? 'option_a'];
          break;
        case 'long_text':
          happy[f.id] = 'This is a synthetic submission generated by the Argo test harness.';
          break;
        case 'file_upload':
          happy[f.id] = 'https://example.com/synth/upload.pdf';
          break;
        case 'short_text':
        default:
          happy[f.id] = 'Synthetic Value';
          break;
      }
    }

    cases.push({
      name: 'happy_path_submission',
      submission: { name: 'happy', path: '/submissions', payload: happy },
      assertions: [
        { kind: 'http_status', expected: 202 },
        { kind: 'response_body_contains', expected: 'submissionId' },
        { kind: 'mongo_document_exists', collection: 'submissions', query: {} },
        { kind: 'approval_token_created' },
      ],
    });

    // Edge: missing required field on the FIRST required field, if any.
    const firstRequired = map.trigger.fields.find((f) => f.required);
    if (firstRequired) {
      const broken = { ...happy };
      delete broken[firstRequired.id];
      cases.push({
        name: 'missing_required_field',
        submission: { name: 'broken', path: '/submissions', payload: broken },
        assertions: [
          { kind: 'http_status', expected: 400 },
          { kind: 'response_body_contains', expected: 'invalid_submission' },
        ],
      });
    }
  }

  // Health check.
  cases.push({
    name: 'health',
    submission: { name: 'health', path: '/health', payload: {} },
    assertions: [{ kind: 'http_status', expected: 200 }],
  });

  return cases;
}
