// "What this does" — the human-readable README for an Argo operation.
// A small pill in the workspace header that opens a modal with three
// sections: What it does, How it works, If something breaks.
//
// The README is generated by GPT-5.5 from the brief + bundle inventory
// and cached server-side per (operationId, bundleVersion) so the modal
// opens instantly after the first miss.

import { useEffect, useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  BookOpen,
  Copy,
  Loader2,
  RefreshCw,
  Sparkles,
  X,
} from 'lucide-react';
import { operations } from '../api/client.js';
import { cn } from '../lib/utils.js';

interface OperationReadmeButtonProps {
  operationId: string;
}

interface ReadmeData {
  bundleVersion: number | null;
  generatedAt: string;
  cached: boolean;
  readme: {
    title: string;
    oneLine: string;
    whatItDoes: string;
    howItWorks: string;
    ifSomethingBreaks: string;
  };
  markdown: string;
}

export function OperationReadmeButton({ operationId }: OperationReadmeButtonProps) {
  const [open, setOpen] = useState(false);
  const [data, setData] = useState<ReadmeData | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [regenerating, setRegenerating] = useState(false);
  const [copied, setCopied] = useState(false);

  const load = async (force: boolean) => {
    setLoading(!force);
    setRegenerating(force);
    setError(null);
    try {
      const res = await operations.readme(operationId, force);
      setData(res);
    } catch (err) {
      const msg = String((err as { message?: string })?.message ?? err);
      if (msg.includes('no_brief_yet')) {
        setError('Finish scoping first — Argo writes the README from your brief.');
      } else {
        setError(msg.slice(0, 200));
      }
    } finally {
      setLoading(false);
      setRegenerating(false);
    }
  };

  useEffect(() => {
    if (!open || data) return;
    void load(false);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open]);

  // Reset cached data if the operation changes.
  useEffect(() => {
    setData(null);
    setError(null);
    setOpen(false);
  }, [operationId]);

  // Esc closes the modal.
  useEffect(() => {
    if (!open) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') setOpen(false);
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [open]);

  const copy = async () => {
    if (!data) return;
    try {
      await navigator.clipboard.writeText(data.markdown);
      setCopied(true);
      setTimeout(() => setCopied(false), 1400);
    } catch {
      /* best-effort */
    }
  };

  const download = () => {
    if (!data) return;
    const blob = new Blob([data.markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${data.readme.title.replace(/[^a-z0-9]+/gi, '-').toLowerCase()}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <>
      <button
        type="button"
        onClick={() => setOpen(true)}
        title="What this operation does — plain English"
        className="inline-flex items-center gap-1.5 rounded-full border border-argo-border bg-argo-surface/40 px-2.5 py-0.5 text-xs text-argo-textSecondary hover:text-argo-text hover:border-argo-accent/40 transition-colors font-mono"
      >
        <BookOpen className="h-3 w-3" />
        <span>About</span>
      </button>

      <AnimatePresence>
        {open && (
          <motion.div
            key="overlay"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.15 }}
            onClick={() => setOpen(false)}
            className="fixed inset-0 z-40 bg-black/65 backdrop-blur-sm flex items-center justify-center p-6"
          >
            <motion.div
              key="modal"
              initial={{ opacity: 0, y: 12, scale: 0.98 }}
              animate={{ opacity: 1, y: 0, scale: 1 }}
              exit={{ opacity: 0, y: -8, scale: 0.98 }}
              transition={{ duration: 0.2, ease: [0.16, 1, 0.3, 1] }}
              onClick={(e) => e.stopPropagation()}
              className="w-full max-w-2xl max-h-[85vh] flex flex-col rounded-2xl border border-argo-border bg-argo-surface shadow-2xl shadow-black/40 overflow-hidden"
            >
              <header className="flex items-center justify-between border-b border-argo-border px-5 h-12 flex-shrink-0">
                <div className="flex items-center gap-2 text-argo-text min-w-0">
                  <Sparkles className="h-4 w-4 text-argo-accent flex-shrink-0" />
                  <span className="text-sm">What this operation does</span>
                  {data?.bundleVersion != null && (
                    <span className="text-[10px] uppercase tracking-widest text-argo-textSecondary font-mono">
                      · v{data.bundleVersion}
                      {data.cached && ' · cached'}
                    </span>
                  )}
                </div>
                <div className="flex items-center gap-2">
                  {data && (
                    <>
                      <button
                        type="button"
                        onClick={copy}
                        title="Copy as Markdown"
                        aria-label="Copy as Markdown"
                        className="text-argo-textSecondary hover:text-argo-text"
                      >
                        {copied ? (
                          <span className="text-[10px] uppercase tracking-widest text-argo-green">copied</span>
                        ) : (
                          <Copy className="h-3.5 w-3.5" />
                        )}
                      </button>
                      <button
                        type="button"
                        onClick={download}
                        title="Download as Markdown"
                        aria-label="Download as Markdown"
                        className="text-argo-textSecondary hover:text-argo-text text-[10px] uppercase tracking-widest"
                      >
                        .md
                      </button>
                      <button
                        type="button"
                        onClick={() => void load(true)}
                        disabled={regenerating}
                        title="Regenerate from current brief + bundle"
                        aria-label="Regenerate"
                        className="text-argo-textSecondary hover:text-argo-text disabled:opacity-40"
                      >
                        <RefreshCw className={cn('h-3.5 w-3.5', regenerating && 'animate-spin')} />
                      </button>
                    </>
                  )}
                  <button
                    type="button"
                    onClick={() => setOpen(false)}
                    aria-label="Close"
                    className="text-argo-textSecondary hover:text-argo-text"
                  >
                    <X className="h-4 w-4" />
                  </button>
                </div>
              </header>

              <div className="flex-1 overflow-y-auto px-6 py-5">
                {loading && !data ? (
                  <div className="flex items-center justify-center py-16 text-argo-textSecondary text-sm">
                    <Loader2 className="h-4 w-4 animate-spin mr-2" /> Argo is writing the README…
                  </div>
                ) : error ? (
                  <div className="flex items-center justify-center py-16 text-center text-argo-amber text-sm px-8">
                    {error}
                  </div>
                ) : data ? (
                  <article className="argo-body text-argo-text">
                    <h1
                      className="argo-hero text-3xl text-argo-text mb-2"
                      style={{ letterSpacing: '-0.05em', lineHeight: 1.1 }}
                    >
                      {data.readme.title}
                    </h1>
                    <p className="text-argo-accent text-base italic mb-6">
                      {data.readme.oneLine}
                    </p>

                    <Section title="What this does" body={data.readme.whatItDoes} />
                    <Section title="How it works" body={data.readme.howItWorks} />
                    <Section title="If something breaks" body={data.readme.ifSomethingBreaks} />

                    <div className="mt-8 pt-4 border-t border-argo-border/60 text-[11px] text-argo-textSecondary font-mono">
                      Generated {formatRelative(data.generatedAt)} · regenerates when the bundle version bumps.
                    </div>
                  </article>
                ) : null}
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </>
  );
}

function Section({ title, body }: { title: string; body: string }) {
  const paragraphs = body.split(/\n\n+/);
  return (
    <section className="mb-6">
      <h2
        className="argo-hero text-lg text-argo-text mb-2"
        style={{ letterSpacing: '-0.03em' }}
      >
        {title}
      </h2>
      {paragraphs.map((p, i) => (
        <p key={i} className="text-argo-text text-[15px] leading-relaxed mb-3 last:mb-0">
          {p}
        </p>
      ))}
    </section>
  );
}

function formatRelative(iso: string): string {
  const d = new Date(iso);
  const ms = Date.now() - d.getTime();
  if (ms < 60_000) return 'just now';
  if (ms < 3_600_000) return `${Math.round(ms / 60_000)}m ago`;
  if (ms < 86_400_000) return `${Math.round(ms / 3_600_000)}h ago`;
  return `${Math.round(ms / 86_400_000)}d ago`;
}
