#requires -Version 5.1
<#
.SYNOPSIS
  One-shot bootstrap for Argo. Walks the operator through the four secrets
  the app needs and writes them to .env.local — never to git, never echoed
  to the screen, never to chat.

.DESCRIPTION
  - Reads the current .env.local (if any) and preserves anything already set.
  - Prompts only for the keys that are still empty.
  - Each key is read with Read-Host -AsSecureString so it never appears on
    screen or in shell history.
  - Generates 64-char hex secrets for SESSION_SECRET, COOKIE_SECRET, and
    INTERNAL_API_KEY automatically (no human-typed entropy).
  - Verifies .env.local is gitignored before writing.

.USAGE
  From the Argo repo root, in PowerShell:
    powershell -ExecutionPolicy Bypass -File scripts\argo-bootstrap.ps1
#>

$ErrorActionPreference = 'Stop'

function Read-SecureString {
  param([string]$Prompt)
  $secure = Read-Host -Prompt $Prompt -AsSecureString
  $bstr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
  try {
    return [Runtime.InteropServices.Marshal]::PtrToStringBSTR($bstr)
  } finally {
    [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr)
  }
}

function Get-RandomHex {
  param([int]$Bytes = 32)
  $buf = New-Object byte[] $Bytes
  [Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($buf)
  -join ($buf | ForEach-Object { '{0:x2}' -f $_ })
}

function Read-DotEnvFile {
  param([string]$Path)
  $map = [ordered]@{}
  if (-not (Test-Path $Path)) { return $map }
  Get-Content -LiteralPath $Path | ForEach-Object {
    $line = $_
    if ($line -match '^\s*#' -or $line -match '^\s*$') { return }
    if ($line -match '^\s*([A-Z_][A-Z0-9_]*)\s*=\s*(.*)$') {
      $map[$matches[1]] = $matches[2]
    }
  }
  return $map
}

function Write-DotEnvFile {
  param(
    [string]$Path,
    [System.Collections.IDictionary]$Map
  )
  $sb = New-Object System.Text.StringBuilder
  $null = $sb.AppendLine('# Argo .env.local — generated by scripts/argo-bootstrap.ps1')
  $null = $sb.AppendLine('# DO NOT COMMIT. DO NOT PASTE INTO CHAT. ROTATE QUARTERLY.')
  $null = $sb.AppendLine('')
  foreach ($k in $Map.Keys) {
    $null = $sb.AppendLine("$k=$($Map[$k])")
  }
  [IO.File]::WriteAllText($Path, $sb.ToString(), (New-Object System.Text.UTF8Encoding($false)))
}

# ── Locate repo root + verify gitignore ─────────────────────────────────
$root = Split-Path -Parent $PSScriptRoot
Set-Location $root

if (-not (Test-Path '.gitignore')) {
  Write-Host 'ERROR: no .gitignore in repo root. Refusing to write secrets.' -ForegroundColor Red
  exit 2
}
$ignored = Select-String -Path '.gitignore' -Pattern '(^|\n)\s*\.env(\.local|\*)?\s*$' -Quiet
if (-not $ignored) {
  Write-Host 'ERROR: .env.local is not gitignored. Add ".env.local" to .gitignore first.' -ForegroundColor Red
  exit 3
}

$envPath = Join-Path $root '.env.local'
$current = Read-DotEnvFile $envPath

# Seed from .env.example so every var the app expects is present.
$template = Read-DotEnvFile (Join-Path $root '.env.example')
$merged = [ordered]@{}
foreach ($k in $template.Keys) {
  if ($current.Contains($k) -and $current[$k] -ne '' -and $current[$k] -ne 'replace_with_64_hex_chars') {
    $merged[$k] = $current[$k]
  } else {
    $merged[$k] = $template[$k]
  }
}

Write-Host ''
Write-Host '════════════════════════════════════════════════════════════' -ForegroundColor Cyan
Write-Host '  Argo bootstrap — local secret setup' -ForegroundColor Cyan
Write-Host '════════════════════════════════════════════════════════════' -ForegroundColor Cyan
Write-Host ''
Write-Host 'This writes to .env.local (gitignored). Nothing leaves your machine.' -ForegroundColor Gray
Write-Host 'Press Enter to skip a key you already have, or paste a fresh value.' -ForegroundColor Gray
Write-Host ''

# ── Auto-generate the three internal hex secrets if missing ─────────────
foreach ($name in @('SESSION_SECRET','COOKIE_SECRET','INTERNAL_API_KEY','AGENTMAIL_INBOUND_WEBHOOK_SECRET','PII_LOG_SALT')) {
  $val = $merged[$name]
  if (-not $val -or $val -eq '' -or $val -like 'replace_with_*') {
    $merged[$name] = Get-RandomHex 32
    Write-Host "  ✓ $name  generated (64 hex)" -ForegroundColor Green
  } else {
    Write-Host "  • $name  kept (already set)" -ForegroundColor DarkGray
  }
}

# ── Provider keys — prompt only for empty ones ──────────────────────────
$prompts = [ordered]@{
  'OPENAI_API_KEY'       = 'OpenAI API key (sk-... or sk-proj-...)'
  'ANTHROPIC_API_KEY'    = 'Anthropic API key (sk-ant-...) — optional, press Enter to skip'
  'EMERGENT_API_KEY'     = 'Emergent universal key (sk-emergent-...) — optional'
  'BLAXEL_API_KEY'       = 'Blaxel API key (bl_...)'
  'BLAXEL_WORKSPACE'     = 'Blaxel workspace name (e.g. algorythm)'
  'AGENTMAIL_API_KEY'    = 'AgentMail API key — optional, press Enter for Mailpit dev mode'
  'AGENTMAIL_FROM_ADDRESS' = 'AgentMail from-inbox (e.g. argoai@agentmail.to) — optional'
}

foreach ($name in $prompts.Keys) {
  $existing = $merged[$name]
  $hasReal = $existing -and $existing -ne '' -and -not ($existing -like 'replace_with_*')
  if ($hasReal) {
    Write-Host "  • $name  kept (already set)" -ForegroundColor DarkGray
    continue
  }
  $label = "  → $($prompts[$name])"
  $value = if ($name -like '*WORKSPACE*' -or $name -like '*FROM_ADDRESS*') {
    Read-Host -Prompt $label
  } else {
    Read-SecureString -Prompt $label
  }
  if ($value -and $value.Length -gt 0) {
    $merged[$name] = $value
  }
}

# ── Wire feature flags so the app uses real services where keys exist ───
$merged['BLAXEL_ENABLED']    = if ($merged['BLAXEL_API_KEY'] -and $merged['BLAXEL_API_KEY'] -ne '') { 'true' } else { 'false' }
$merged['AGENTMAIL_ENABLED'] = if ($merged['AGENTMAIL_API_KEY'] -and $merged['AGENTMAIL_API_KEY'] -ne '') { 'true' } else { 'false' }
$merged['EMERGENT_ENABLED']  = if ($merged['EMERGENT_API_KEY'] -and $merged['EMERGENT_API_KEY'] -ne '') { 'true' } else { 'false' }

Write-DotEnvFile -Path $envPath -Map $merged

Write-Host ''
Write-Host '════════════════════════════════════════════════════════════' -ForegroundColor Green
Write-Host "  Wrote $envPath" -ForegroundColor Green
Write-Host '════════════════════════════════════════════════════════════' -ForegroundColor Green
Write-Host ''
Write-Host 'Next steps:' -ForegroundColor Cyan
Write-Host '  pnpm infra:up      # start postgres + mongo + redis + mailpit'
Write-Host '  pnpm db:generate'
Write-Host '  pnpm db:migrate'
Write-Host '  pnpm dev           # web on :5173, api on :4000'
Write-Host ''
Write-Host 'If the keys you pasted have ever been in chat or shared, ROTATE THEM' -ForegroundColor Yellow
Write-Host 'in the provider consoles before going to production.' -ForegroundColor Yellow
Write-Host ''
